# ============================
# 🔵 BASE DE DATOS POSTGRESQL
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/login
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ============================
# 🔐 JWT
# ============================
app.jwtSecret=ChangeThisSecretForProd!
app.jwtExpirationMs=3600000

# ============================
# 🌐 SERVER
# ============================
server.port=8082
